title: Abdelrahman Elmeniawy
email: ameniawy18@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website! I'm Abdelrahman Elmeniawy a Software
  Engineer based in Berlin, Germany.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.aelmeniawy.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ameniawy
github_username: ameniawy

# Build settings
theme: minima
plugins:
  - jekyll-feed
